# Perfil activo por defecto: development (local)
spring.profiles.active=dev

# Configuracion JPA comun a todos los perfiles
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect